---
- name: Create mysql database
  mysql_db: name={{ wp_db_name }} state=present
  become: yes

- name: Create mysql user
  mysql_user: 
    name={{ wp_db_user }} 
    password={{ wp_db_password }} 
    priv=*.*:ALL

  become: yes  
