---
- hosts: localhost
  become: yes
  tasks:
          - name: chaljamerijann
            ec2:
                    aws_access_key: AKIA5WRIVFTK2P6IT2EK
                    aws_secret_key: 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
                    region: us-east-1





           
          - ec2_instance_info:
                      filters: 
                         "tag:Name": ansible
             

             #  - debug:
             #      msg: "{{ ec2 }}"
             #
             # - name: add host
             # add_host:
             #       name: "{{ item }}"
             #       groupname: launched
             #  with_items: " {{ ec2.stdout }}"


             #           - name: get the ip automatically in inventory
             #             lineinfile:
             #                     path: /home/ansible/aws/inventory
             #                     line: "{{ ec2_results.stdout }}"
             #                     create: yes
             #             become: yes

