---
 - name: Download WordPress
   get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

 - name: Extract WordPress
   unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
   become: yes


 - name: Wordpresss | Remove wordpress-{{wp_version}}.tar.gz
   file: path=/tmp/wordpress.tar.gz state=absent


 - name: Wordpresss | Fetch random salts for wp-config.php
   local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
   # sudo: yes
   register: 'wp_salt'


 - name: Update default httpd site
   become: yes
   lineinfile:
    dest=/etc/httpd/conf/httpd.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
    state=present
    backup=yes
   notify:
    - restart httpd

 - name: create a file
   command: touch /var/www/wordpress/wp-config.php


 - name: Wordpresss | Copy wp-config.php file
   template: src=wp-config.php.j2 dest=/var/www/wordpress/wp-config.php


 - name: update wordpress config file
   lineinfile:
     dest: /var/www/wordpress/wp-config.php
     regexp: "{{ item.regexp }}"
     line: "{{ item.line }}"
   with_items:
       - {'regexp': " define\\('DB_NAME', '(.)+'\\);",'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
       - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
       - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
   become: yes



