---
- hosts: localhost
  become: yes
  gather_facts: false
  tasks:
          - name: log into the MIS
            uri:
                    url: http://mis.neosofttech.in/
                    method: POST
                    body_format: json

                    #                    body: "Email Address=harsha.sakhare@neosofttech.com&Password=harshas123&IP Address=10.0.60.236&Location=Prabhadevi-Bussiness Arcade (8th Floor)&enter=Login"
                    status_code: 302
                    force_basic_auth: yes         
                    headers:
                       Content-Type: "application/x-www-form-urlencoded"
                    register: login

                       
                    
                    


