---
  
 - name: Launch instance
   ec2:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      key_name: "{{ keypair }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami }}"  
      wait: true
      region: "{{ region }}"
      vpc_subnet_id: "{{ subnet }}"
      assign_public_ip: yes
      instance_tags: Name=ansible
      # register: ec2_instances
 

 - name: aws cli for public ip
   shell: aws ec2 describe-instances --filter "Name=tag:Name,Values=ansible"| jq -r '.Reservations[].Instances[].PublicIpAddress' 
   register: ec2_instances

 - name: addhost
   add_host:
           hostname: "{{ ec2_instances }}"
           groupname: new
           inventory_dir: /home/ansible/aws/autoinv/new   
       







             #           - name: get the ip automatically in inventory
             #             lineinfile:
             #                     path: /home/ansible/aws/inventory
             #                     line: "{{ ec2_results.stdout }}"
             #                     create: yes
             #             become: yes
             #                
           
    
